### ISSUE TITLE
为什么这个仓库不同步到Packagist？

### ISSUE THREAD

**Issue by xiebruce** [huaweicloud/huaweicloud-sdk-php-obs#14]
为什么在[SDK下载](https://support.huaweicloud.com/sdk-php-devg-obs/obs_28_0001.html)里不说一下composer怎么安装？我直接去[Packagist](https://packagist.org/?query=huaweicloud)查`huaweicloud`并没有一个是从这边官方仓库提交过去的，也就是说那些都是个人提交的吗？
![image](https://user-images.githubusercontent.com/13575500/77494630-30fdd700-6e81-11ea-98c1-47604a8efdb7.png)

**Comment by sy-records** [comment]
包名是这个obs/esdk-obs-php

**Comment by sy-records** [comment]
composer require obs/esdk-obs-php

**Comment by xiebruce** [comment]
@sy-records 哦哦，谢谢，他们的文档也没有说明包名是这个——不，是根本没提composer这回事，所以我没猜出来，总以为带华为的拼音
![image](https://user-images.githubusercontent.com/13575500/77531611-2a498100-6ece-11ea-97e8-df628f8d3e3d.png)

这里的READMD.md也不写一下composer安装。。。真是无语，国际大公司就是牛，要靠我们自己去查去找去猜去问。

**Comment by sy-records** [comment]
我有个pr在提交，加了安装- -。#13
-----
是啊，华为的这个开源好像不太行，有一个模板库，居然不用它。https://github.com/huaweicloud/repo-template

**Comment by xiebruce** [comment]
@sy-records 就是，有模板都不用

**Comment by sy-records** [comment]
其他的库应该是官方不合并pr自己搞的。。。

**Comment by xiebruce** [comment]
哈哈，估计是吧，不合并就不合并了，关键根本没动静，它也不说为什么不合并，它也不拒绝，它也不同意

**Comment by hongfs** [comment]
php 可能不是重点。

**Comment by xiebruce** [comment]
也许他们已经放弃了

**Comment by xiebruce** [comment]
![image](https://user-images.githubusercontent.com/13575500/77611903-8f9a8200-6f61-11ea-8270-a60be8542a29.png)
我这边的monolog现在是1.24，所以不行
