### ISSUE TITLE
为什么 依赖库的版本是固定的？

### ISSUE THREAD

**Issue by lyc2468** [huaweicloud/huaweicloud-sdk-php-obs#15]
这样对已有项目不友好

**Comment by xin6841414** [comment]
帮顶， 在laravel5.8上安装 报monolog/monolog冲突，现有1.25.3, obs 依赖1.23.0

**Comment by xwpd** [comment]
同样遇到这个问题，是在想不到会这样，本来打算使用sdk的，现在不能指望了。。。

**Comment by redabc** [comment]
下个版本我们我升级依赖包
