### ISSUE TITLE
华为这样一个技术公司的sdk连用composer安装都不支持吗？

### ISSUE THREAD

**Issue by xiebruce** [huaweicloud/huaweicloud-sdk-php-obs#5]
希望能上传到[packagist.org](https://packagist.org)，以便支持composer方式安装，小厂不支持也就算了，你华为这样一个国内外有名的公司竟然连composer都不支持，有点说不过去呀。

![image](https://user-images.githubusercontent.com/13575500/61518929-4f334d80-aa3d-11e9-9d20-ef779ed1b325.png)

**Comment by namet117** [comment]
[机票](https://support.huaweicloud.com/sdk-php-devg-obs/zh-cn_topic_0142811829.html)

**Comment by xiebruce** [comment]
好的，谢谢！

**Comment by Leslack-hub** [comment]
还有机票吗?
