### ISSUE TITLE
psr/log版本太低了

### ISSUE THREAD

**Issue by xuhuaiqu** [huaweicloud/huaweicloud-sdk-php-obs#6]
psr/log 还是1.0.2的版本 这是个版本还是16年的。连laravel5.5这种好几年前的框架都没法集成。请升级psr/log到最新1.1.0的。

**Comment by xuhuaiqu** [comment]
已经提了一个pull requests 请合并～

**Comment by lihe6666** [comment]
谢谢。

> 已经提了一个pull requests 请合并～

**Comment by zeroone2005** [comment]
哎真麻烦。官方也不合并，安装很语言
